---
title: "SC_data"
output: html_document
date: "2026-09-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(Seurat)
library(tidyverse)
library(DropletUtils)
library(Matrix)
library(data.table)

setwd("/gpfs1/pi/kmccreer/scRNAseq/issy_26-27/honors_thesis")

```

```{r}
'''
Just one data object: 
# Read the dense matrix
dt <- fread("GSM3516662_MSK_LX653_PRIMARY_TUMOUR_dense.csv.gz")
dt <- as.data.frame(dt)   

# transposing matrix and formatting row names
dt <- t(dt)
rownames(dt) <- make.unique(rownames(dt))

# creating Seurat object
# need to decide on filtering parameters... look back at old work
## min.cells will filter genes in less than x cells and min.features will filter cells with less than y genes expressed
object <- CreateSeuratObject(dt, project = "thesis", assay = "RNA", min.cells = 3, min.features = 200, names.field = 1,
  names.delim = "_", meta.data = NULL)

object
# use merge to combine my Seurat objects
# going to need to loop through my list of files
'''
```


```{r}
# list of my files
List_of_files =  c("GSM3516662_MSK_LX653_PRIMARY_TUMOUR_dense.csv.gz", "GSM3516663_MSK_LX661_PRIMARY_TUMOUR_dense.csv.gz", "GSM3516664_MSK_LX666_METASTASIS_dense.csv.gz", "GSM3516665_MSK_LX675_PRIMARY_TUMOUR_dense.csv.gz", "GSM3516666_MSK_LX675_NORMAL_dense.csv.gz", "GSM3516667_MSK_LX676_PRIMARY_TUMOUR_dense.csv.gz", "GSM3516668_MSK_LX255B_METASTASIS_dense.csv.gz",  "GSM3516669_MSK_LX679_PRIMARY_TUMOUR_dense.csv.gz", "GSM3516670_MSK_LX680_PRIMARY_TUMOUR_dense.csv.gz", "GSM3516671_MSK_LX681_METASTASIS_dense.csv.gz", "GSM3516672_MSK_LX682_PRIMARY_TUMOUR_dense.csv.gz", "GSM3516673_MSK_LX682_NORMAL_dense.csv.gz",   "GSM3516674_MSK_LX684_PRIMARY_TUMOUR_dense.csv.gz",  "GSM3516675_MSK_LX684_NORMAL_dense.csv.gz",   "GSM3516676_MSK_LX685_NORMAL_dense.csv.gz", "GSM3516677_MSK_LX699_METASTASIS_dense.csv.gz",   "GSM3516678_MSK_LX701_METASTASIS_dense.csv.gz" )

# make sure you specify more than 4 (mb??) of data for each R session

for(x in List_of_files){
  name <- gsub('_matrix', '', x)
  dt <- fread(x)
  dt <- as.data.frame(dt)
  dt <- t(dt)
  rownames(dt) <- make.unique(rownames(dt))
  assign(name, CreateSeuratObject(dt, project = "thesis", assay = "RNA", min.cells = 3, min.features = 200, names.field = 1,
  names.delim = "_", meta.data = NULL))
}

merged_object <- merge(GSM3516662_MSK_LX653_PRIMARY_TUMOUR_dense.csv.gz, y = c(GSM3516663_MSK_LX661_PRIMARY_TUMOUR_dense.csv.gz, GSM3516664_MSK_LX666_METASTASIS_dense.csv.gz, GSM3516665_MSK_LX675_PRIMARY_TUMOUR_dense.csv.gz, GSM3516666_MSK_LX675_NORMAL_dense.csv.gz, GSM3516667_MSK_LX676_PRIMARY_TUMOUR_dense.csv.gz, GSM3516668_MSK_LX255B_METASTASIS_dense.csv.gz,  GSM3516669_MSK_LX679_PRIMARY_TUMOUR_dense.csv.gz, GSM3516670_MSK_LX680_PRIMARY_TUMOUR_dense.csv.gz, GSM3516671_MSK_LX681_METASTASIS_dense.csv.gz, GSM3516672_MSK_LX682_PRIMARY_TUMOUR_dense.csv.gz, GSM3516673_MSK_LX682_NORMAL_dense.csv.gz,   GSM3516674_MSK_LX684_PRIMARY_TUMOUR_dense.csv.gz,  GSM3516675_MSK_LX684_NORMAL_dense.csv.gz,                                                  GSM3516676_MSK_LX685_NORMAL_dense.csv.gz, GSM3516677_MSK_LX699_METASTASIS_dense.csv.gz,  GSM3516678_MSK_LX701_METASTASIS_dense.csv.gz),
      add.cell.ids = List_of_files,
      project = "thesis")

merged_object

```

```{r}
# View(merged_object@meta.data) to see the counts
merged_object$sample <- rownames(merged_object@meta.data)
View(merged_object@meta.data)
head(merged_object@meta.data$sample)
merged_object@meta.data <- separate(merged_object@meta.data, col = 'sample', into = c('barcode', 'MSK', 'LX653', 'Type', 'dense.cv.gz', 'cell', 'number'), sep = '_')

library(stringr)
merged_object$sample <- rownames(merged_object@meta.data)

merged_object@meta.data <- merged_object@meta.data |>
  mutate(sampleName = str_remove_all(sample, "GSM[0-9]+_MSK_|_dense\\.csv\\.gz"))

# continue later on data visualization....

merged_object@meta.data |>
ggplot(aes(x=merged_object@meta.data$orig.indent, fill = merged_object@meta.data$orig.indent)) + 
geom_bar(color="black") +
stat_count(geom = "text", colour = "black", size = 3.5, 
          aes(label = ..count..),
        position=position_stack(vjust=0.5))+
theme_classic() +
theme(plot.title = element_text(hjust=0.5, face="bold")) +
ggtitle("Number of Cells per Sample")

# saveRDS(merged_object,"../merged_seurat_obj_allRNAsamples.rds")


```

